import type { Metadata } from "next";
import "./globals.css";
import NoteList from "@/components/notes/list";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-screen h-screen grid grid-rows-[auto_1fr]">
        <header className="w-full h-fit">
          <h1 className="text-3xl">My Notes</h1>
        </header>
        <div className="grid grid-cols-[auto_1fr]">
          <aside className="min-w-0 sm:min-w-36">
            <h2>Notes</h2>
            <nav>
              <NoteList />
            </nav>
          </aside>
          <main className="p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
